apiVersion: batch/v1
kind: CronJob
metadata:
  name: journal-archiver
  labels:
    app: journal-system
    component: backup
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: archiver
              image: alpine:3.16
              volumeMounts:
                - name: tmp-dir
                  mountPath: /tmp
                - name: archive-dir
                  mountPath: /mnt/backup
              command:
                - sh
                - -exc
                - |
                  echo "Установка необходимых пакетов"
                  apk add --no-cache curl tar

                  LOG_DIR=/tmp/logs
                  ARCHIVE_DIR=/mnt/backup
                  mkdir -p $LOG_DIR

                  echo "Загрузка логов"
                  curl -s http://journal-service/logs > $LOG_DIR/logs.txt

                  ARCHIVE_NAME="journals-$(date +%Y%m%d-%H%M%S).tar.gz"
                  echo "Создание архива $ARCHIVE_NAME..."
                  tar -czf "$ARCHIVE_DIR/$ARCHIVE_NAME" -C /tmp logs

                  echo "Архив создан. Содержимое архива:"
                  ls -lh "$ARCHIVE_DIR"
          volumes:
            - name: tmp-dir
              emptyDir: {}
            - name: archive-dir
              persistentVolumeClaim:
                claimName: journal-archive-pvc
