apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: journal-archive-pvc
  labels:
    app: journal-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
