apiVersion: v1
kind: PersistentVolume
metadata:
  name: journal-archive-pv
  labels:
    app: journal-system
    type: storage
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/journal-archives
    type: DirectoryOrCreate
